### ISSUE TITLE
Mapping to JCL?

### ISSUE THREAD

**Issue by rjhintz** [openmainframeproject/zorow#34]
Do these workflows map to JCL tasks? It would be helpful if the README mentioned what relation, if any, this project and its workflows have to legacy JCL (or CLISTs, REXX).

**Comment by shreeji818** [comment]
Depending of workflows, there are different JCL (REXX or shell scripts) that are included in the workflow steps. @rjhintz I am sorry, I did not understand your comment about mapping to JCL tasks.

**Comment by rjhintz** [comment]
@shreeji818 By mapping to JCL tasks I mean, for example:

- **JCL** compile, link, store in library maps to **zorow**  XXX function
- **JCL** exec job in library maps to **zorow**  YYY function
- **JCL** exec job stream in library maps to **zorow**  ZZZ function stream

I'm trying to understand how one would use **zorow** in place of **JCL**.

**Comment by shreeji818** [comment]
Ahh. Thanks. There is no specific function that "zorow" provides. It's a repository of workflows. So, either IBM or customer can create and share workflows for specific functions. Some one has to create z/OSMF workflow that includes JCL to compile, link and store in library. Same about other tasks mentioned here. IBM GTS shared few workflows in this community. There are ReadMe.md files in each folder in IBM-GTS-Workflows that describes function provided by workflows. Let me know if this clarifies what you are asking for.

**Comment by rjhintz** [comment]
@shreeji818 Thanks. 

To be clear, in order to have, say, a COBOL program compiled, linked, and stored in a library using **zorow**, one has to create a workflow that invokes a JCL job stream using legacy JCL job `EXEC=` steps? 

So one needs to understand JCL vocabulary, grammar, and perhaps site specific constraints?

**Comment by shreeji818** [comment]
@rjhintz Can we close this issue? 
As we discussed, Zorow provides repository that holds z/OSMF workflows provided by IBM and customers. z/OSMF workflows uses JCL, REXX etc to drive work on z/OS. So, user who creates z/OSMF workflows need to have knowledge about JCL (vocabulary, grammar, site specific constraints etc.) and executable (specified with EXEC=) that JCL will drive.

**Comment by rjhintz** [comment]
@shreeji818  Ok, thanks for the clarification. I guess I was looking for a JCL replacement since knowing JCL (which I do) is a real barrier for new people.
